docs/src/overview/runtimes.md
server-common/src/config.rs

and mention 12 factor as a motivation for env-based config
closes #25
@prabirshrestha, does this look good?

document LISTEN_FD support

---

sessions/examples/sessions.rs
sessions/src/session_handler.rs

sessions: add support for secret rotation

---

http/src/conn.rs
websockets/src/lib.rs

support `connection: keep-alive, Upgrade` (firefox)

---

askama/src/lib.rs
async-std/src/lib.rs
aws-lambda/src/lib.rs
client/src/lib.rs
controllers/src/lib.rs
cookies/src/lib.rs
handlebars/src/lib.rs
html-rewriter/src/lib.rs
http/src/lib.rs
logger/src/lib.rs
native-tls/src/lib.rs
proxy/src/lib.rs
router/src/lib.rs
rustls/src/lib.rs
server-common/src/lib.rs
sessions/src/lib.rs
smol/src/lib.rs
static-compiled/src/lib.rs
static/src/lib.rs
tera/src/lib.rs
testing/src/lib.rs
tls-common/src/lib.rs
tokio/src/lib.rs
trillium/src/lib.rs
websockets/src/lib.rs

to rustdoc::missing_crate_level_docs

lint changed from missing_crate_level_docs

---

router/examples/nested-router.rs
router/src/router.rs
router/src/router_ref.rs
router/tests/options.rs

semver-minor, this entails trillium-router 0.2.0

rename router.any to router.all, add router.any which accepts a slice of specific methods

---

Cargo.toml
aws-lambda/Cargo.toml
forwarding/Cargo.toml
forwarding/examples/forwarding.rs
forwarding/src/lib.rs
forwarding/tests/tests.rs
http/Cargo.toml
http/src/conn.rs
logger/src/formatters.rs
testing/Cargo.toml
testing/src/test_conn.rs

also patch-bumps trillium-http, trillium-testing, and trillium-logger

add forwarding handler

---

.github/workflows/ci.yaml
async-std/Cargo.toml
async-std/src/server.rs
docs/src/overview/runtimes.md
server-common/Cargo.toml
server-common/src/binding.rs
server-common/src/config.rs
server-common/src/config_ext.rs
server-common/src/lib.rs
server-common/src/server.rs
smol/Cargo.toml
smol/examples/smol.rs
smol/src/lib.rs
smol/src/server.rs
static-compiled/examples/static-compiled.rs
static-compiled/src/lib.rs
static/examples/static.rs
static/src/lib.rs
testing/Cargo.toml
tokio/Cargo.toml
tokio/src/server.rs
trillium/src/info.rs

closes #87 
to use uds, set the HOST env var to a path

add support for unix domain sockets

---

docs/src/overview/handlers.md

Noticed a bit of a Markdown snafu

Update handlers.md - Correct link syntax

---

Cargo.toml
api/Cargo.toml
api/examples/api.rs
api/src/lib.rs
api/tests/tests.rs

refs #36 
closes #108 
(although there will likely be significant further effort in this regard, and possible alternative crates)

api handler

---

http/src/conn.rs

add Server and Date on conn construction not on send

---

http/src/body.rs

previously, all streamed bodies were sent as chunked, but now we use the presence/absence of length to determine if we should use a chunked encoding.
this pr also adds a notion of progress and exposes `bytes_read`

resolve issue where streaming bodies with known length were chunked

---

Cargo.toml
sse/Cargo.toml
sse/examples/sse.rs
sse/examples/static/index.html
sse/examples/static/index.js
sse/src/lib.rs

support for server-sent-events

---

testing/src/assertions.rs
testing/src/test_conn.rs

trillium-testing minor feature: make TestConn::take_response_body_string sync

---

router/Cargo.toml
router/examples/router.rs
router/src/router.rs

router patch bugfix: no longer use arcs for mounting the same handler on multiple methods

---

websockets/src/json.rs
websockets/src/lib.rs
websockets/src/websocket_connection.rs

websockets patch feature: add support for protocol config

---

tera/src/lib.rs

This allows one to implement the [`Test`](https://docs.rs/tera/latest/tera/trait.Test.html), [`Filter`](https://docs.rs/tera/latest/tera/trait.Filter.html),  and [`Function`](https://docs.rs/tera/latest/tera/trait.Function.html) traits provided by Tera.

tera: Export more traits.

---

client/src/conn.rs

client patch feature: add chainable Conn::with_header

---

client/Cargo.toml
client/examples/client.rs
client/src/conn.rs

also deprecate with_request_body and rename to with_body

client patch feature: add json crate feature

---

proxy/src/lib.rs

previously the proxy did not forward querystrings. now it does

proxy patch bugfix: do not drop querystring

---

http/src/conn.rs

further fix with tests coming shortly, trillium-http testing needs an overhaul

minimum fix for an issue in keepalive predicate

---

router/src/router.rs
router/src/router_ref.rs

accept any TryInto<RouteSpec> instead of &'static str

---

trillium/src/conn.rs

trillium patch feature: add Conn::{set_}peer_ip

---

websockets/src/lib.rs
websockets/src/websocket_connection.rs

websockets patch feature: add WebSocketConn::peer_ip

---

.github/workflows/ci.yaml

this probably isn't useful for this repo, but i thought i'd check it out

run ci on merge groups

---

macros/Cargo.toml
macros/src/lib.rs
macros/tests/derive.rs

make an effort at supporting contained generics

macros minor feature: add better generics support

---

http/Cargo.toml
http/src/method.rs
http/src/status.rs

add serde feature to derive Serialize and Deserialize for Method and Status

---

http/src/headers.rs
proxy/Cargo.toml
proxy/src/lib.rs

Stripping AcceptEncoding is hopefully temporary, but the proxy currently does not correctly pass through compressed content

proxy: insert Forwarded and optionally Via header; strip AcceptEncoding

---

api/src/api_handler.rs

This adds support for init, before_send, has_upgrade, and upgrade. Default error handling is moved to the before_send and is only called when the returned handler is not found, as that indicates that FromConn extraction failed.
This introduces an Arc that can be removed during the next trillium semver-minor by making has_upgrade take a &mut Upgrade instead of &Upgrade.
closes #389 
closes #390

Add support for full Handler sequence in Handlers returned from trillium-api endpoints

---

http/src/conn.rs

this pr:
* decreases the allocated write buffer size
* decreases the allocated header read buffer size and extends it nonlinearly when needed
* avoids writing the first line of the http response to a vec just to copy it into the buffer vec
* avoids copying each header name twice

http patch: perf improvements

---

http/src/received_body.rs
http/src/received_body/tests/chunked.rs

this pr addresses another class of pathological chunked decoder behavior discovered thanks to @divergentdave's fuzzer

http patch bugfix: resolve another chunked decoder bug

---

proxy/Cargo.toml
proxy/examples/proxy.rs
proxy/examples/upstream.rs
proxy/src/lib.rs

and add the example I've been using for testing

proxy: improve handling of get requests

---

client/src/conn.rs

This is extremely minor, but I noticed it while reading through the code for
other reasons.
`size::Size` is already Display, so there's no need to convert it to a
String before using it in a formatting context.

client: Avoid an unnecessary to_string() before formatting

---

client/src/lib.rs
http/src/conn.rs
http/tests/use_cases.rs

http patch reversion: set Server header before request (again)

---

askama/Cargo.toml
askama/src/lib.rs
tera/Cargo.toml
tera/src/tera_conn_ext.rs

mime-db pulled in a bunch of unnecessary dependencies for what should be a minimal-or-no-dependency responsibility

chore(askama,tera): move from mime-db to mime_guess

---

client/Cargo.toml
client/src/client.rs
client/src/conn.rs
client/src/into_url.rs
client/tests/base.rs

release-plz using commit messages for semver detection doesn't work for this

fix(client)!: client use of server-common 0.5 was a breaking change
