docs/src/overview/core_concepts.md
Fixes a typo in the core concepts docs, so the dependencies can be copy-pasted from the docs again.
=> Fix the dependency specification in the core concepts documentation

async-std/src/server.rs, aws-lambda/src/lib.rs, logger/src/lib.rs, server-common/src/config_ext.rs, smol/src/server.rs, testing/src/lib.rs, tokio/src/server.rs, trillium/src/handler.rs, trillium/src/info.rs, trillium/src/init.rs, trillium/src/lib.rs
Provides support for asynchronous initialization of a handler after
the server is started.
```rust
use trillium::{Conn, State, Init};
#[derive(Debug, Clone)]
struct MyDatabaseConnection(String);
impl MyDatabaseConnection {
async fn connect(uri: String) -> std::io::Result<Self> {
Ok(Self(uri))
}
async fn query(&mut self, query: &str) -> String {
format!("you queried `{}` against {}", query, &self.0)
}
}
let mut handler = (
Init::new(|_| async {
let url = std::env::var("DATABASE_URL").unwrap();
let db = MyDatabaseConnection::connect(url).await.unwrap();
State::new(db)
}),
|mut conn: Conn| async move {
let db = conn.state_mut::<MyDatabaseConnection>().unwrap();
let response = db.query("select * from users limit 1").await;
conn.ok(response)
}
);
std::env::set_var("DATABASE_URL", "db://db"); …
```
=> Pass a new `Info` struct to init and add an `Init` handler

http/src/conn.rs, http/src/synthetic.rs, logger/src/lib.rs
motivation:
- having full end-to-end timing in Logger
- providing a hook for applications to spawn async tasks outside of the http conn cycle (#49)
- other telemetry (https://twitter.com/algo_luca/status/1404194564123078662)
This would be trillium-http v0.1.3 and trillium-logger v0.1.2
=> add an after_send callback on trillium_http::Conn

http/src/conn.rs, trillium/src/conn.rs
partially addresses #6. Maybe it would be best if querystrong was implemented as a distinct crate, as some people may want to use serde_qs
semver: patch, straightforward addition. trillium 0.1.3 and trillium-http 0.1.3
=> add conn.querystring to both trillium-http and trillium

http/src/conn.rs
This closes #67
The bue was due to the `after_send` callback waiting for the beginning of the _next_ http cycle if the tcp connection was held open for keepalive
=> bugfix: after send waited for next keepalive req

http/src/conn.rs
this was a misread of the spec — it is valid to have neither c-l or t-e
=> handle absence content-length AND transfer-encoding

http/examples/http.rs, http/examples/tokio-http.rs, http/src/conn.rs, http/src/synthetic.rs, testing/src/assertions.rs, trillium/src/conn.rs
this is a breaking change so it's going into the trillium/0.2.0 line
=> Trillium http/response headers mut

router/src/lib.rs, router/src/router.rs, router/src/router_ref.rs, router/tests/options.rs
closes #62 
By default, the trillium router will reply to an OPTIONS request with
the list of supported http methods at the given route. If the OPTIONS
request is sent for `*`, it responds with the full set of http methods
supported by this router.
**Note:** This behavior is superceded by an explicit OPTIONS handler
or an `any` handler.
To disable the default OPTIONS behavior, use
`Router::without_options_handling` or
`RouterRef::set_options_handling`
=> add optional support for OPTIONS handling

.github/workflows/ci.yaml, async-std/Cargo.toml, async-std/examples/async-std.rs, async-std/src/lib.rs, http/src/received_body.rs, server-common/src/clone_counter.rs, smol/Cargo.toml, smol/examples/smol.rs, smol/src/lib.rs, testing/Cargo.toml, testing/src/assertions.rs, testing/src/lib.rs, testing/src/test_conn.rs, testing/src/with_server.rs, tokio/Cargo.toml, tokio/examples/tokio.rs, tokio/src/lib.rs, tokio/src/server.rs, tokio/tests/tests.rs, trillium/src/conn.rs
closes #73 
The default runtime for trillium_testing is smol. To test a
trillium_tokio or trillium_async_std application:
```toml
[dev-dependencies.trillium-testing]
version = "0.1"
default-features = false
features = ["tokio"]
[dev-dependencies]
trillium_testing = { version = "0.1", default-features = false, features = ["tokio"] }
```
```toml
[dev-dependencies.trillium-testing]
version = "0.1"
default-features = false
features = ["async-std"]
[dev-dependencies]
trillium_testing = { version = "0.1", default-features = false, features = ["async-std"] }
```
This PR entails trillium-tokio@0.1.3, trillium-async-std@0.1.3, trillium-smol@0.1.3 and trillium-testing@0.1.2
=> add feature flags to support testing non-async-global-executor apps

.gitignore, async-std/Cargo.toml, async-std/src/server.rs, forwarding/src/lib.rs, http/Cargo.toml, http/src/lib.rs, logger/examples/logger.rs, server-common/Cargo.toml, server-common/src/config.rs, server-common/src/config_ext.rs, server-common/src/server.rs, smol/Cargo.toml, smol/src/server.rs, tokio/Cargo.toml, tokio/src/server.rs
send a static 503 response when we are over capacity but under the ulimit. additionally, this pr addresses an issue where we'd previously shut down if the ulimit was reached. now we just log an error and keep trucking
this pr entails patch releases to trillium-http, trillium-server-common, and all of the runtime adapters
=> add support for max_connections

websockets/Cargo.toml, websockets/src/websocket_connection.rs
and make path only return the non-querystring component. also as long as making a breaking change, return Method instead of &Method
closes #89
=> add WebsocketConnection::querystring

http/src/body.rs
=> Fix BodyType::Static for filesizes greater than 8192 bytes

trillium/src/init.rs, trillium/src/lib.rs
as an alias for `trillium::Init::new`, for consistency with `trillium::state` as an alias for `trililum::State::new`
=> trillium patch feature: add trillium::init

caching-headers/Cargo.toml, static/Cargo.toml, testing/Cargo.toml, testing/src/lib.rs
Enable smol as runtime for docs.rs builds, issue #202 
I took the liberty to also:
- Fix minor documentation error in testing
- Enable smol feature for static in caching headers
Should I update crate versions as well?
=> fix failing docs build for testing & static

client/Cargo.toml, client/src/conn.rs, logger/Cargo.toml, logger/src/formatters.rs, proxy/Cargo.toml, proxy/src/lib.rs
To prevent future breakage, the `size` crate now uses the builder pattern for
formatting sizes as strings instead of taking hard-coded parameters for the
various knobs and settings.
This lets you also only set the settings you wish to override (Base2 to Base10).
(I'm not expecting any more breaking changes and apologize for the churn!)
=> Upgrade `size` dependency to 0.4

http/Cargo.toml, http/src/headers.rs, http/src/http_compat.rs, http/src/lib.rs
This enables easier interop with `http`-crate types (in this case the oauth2 library). This feature offers some conversion implementations. they're not particularly efficient as of this version (size hints are ignored on headers, there are some unnecessary clones) but they get it done.
The only change outside of the feature is to add a derived implementation of PartialEq and Eq to `trillium_http::Headers`, the previous absence of which was an oversight.
=> http patch feature: add http-compat feature

http/src/conn.rs
this seems to be the standard max length elsewhere
=> http patch: increase MAX_HEAD_LENGTH to 8kb

Cargo.toml, http/src/header_value.rs, http/src/header_values.rs, redirect/Cargo.toml, redirect/src/lib.rs
This adds a small redirection crate, which would be a strong candidate for inclusion in the `trillium` crate if there isn't any api churn
=> Redirection

logger/Cargo.toml, logger/src/formatters.rs, logger/src/lib.rs, logger/tests/apache.rs
also deprecate formatters::header in preference to request_header, add response_header, make both headers take `impl Into<HeaderName<'static>>`
=> Logger: use time crate instead of chrono

trillium/src/init.rs
It was a mistake that it was not originally FnOnce, but relaxing from Fn to FnOnce is semver-patch. It also could take `&mut Info` now that it's FnOnce, but that would be a semver-minor change
=> trillium patch feature: init fn can be FnOnce

cookies/src/cookies_handler.rs, sessions/src/session_handler.rs
If the conn has a CookieJar or Session previously set on it, we use that. With this change, trillium_testing::TestConn can explicitly provide a Session or CookieJar prior to the application running
=> cookies and sessions minor feature: use CookieJar and Session from state for testing purposes

.github/workflows/ci.yaml, client/Cargo.toml, http/src/lib.rs
closes #362, which was previously not considered a bug but the fix is harmless
=> Http doctest no features

.github/workflows/coverage.yml, async-std/src/lib.rs, async-std/src/server/tcp.rs, async-std/src/server/unix.rs, codecov.yml, server-common/src/config.rs, server-common/src/server.rs, smol/src/lib.rs, smol/src/server/tcp.rs, smol/src/server/unix.rs, tokio/examples/tokio_binding.rs, tokio/src/lib.rs, tokio/src/server/tcp.rs, tokio/src/server/unix.rs
=> Config with listener

server-common/src/acceptor.rs
`TlsStream<Input>` without the backquotes lets markdown interpret
`<Input>` as HTML, which looks like this:
=> Fix rustdoc syntax to avoid interpretation as HTML

rustls/Cargo.toml, rustls/src/client.rs
This avoids the extra dependencies on openssl-probe and the probe for
native certificates on a server that will never have them installed.
I made native-roots a default feature for compatibility, but in a future
breaking-change version, you might consider making it non-default.
=> trillium-rustls: Make native root support optional

trillium/src/conn.rs
trillium_http::Conn supports returning a borrow of the response body,
but trillium:Conn doesn't have a corresponding method.
This is useful for examining a response body non-destructively without
having to take it and re-set it afterwards.
=> Add trillium::Conn::response_body() to borrow the response body

server-common/src/config.rs, tokio/examples/tokio_binding.rs
=> Allow nodelay on prebound server

http/Cargo.toml, http/src/bufwriter.rs
when we hit the buffer's capacity, do a vectored write until the buffer is consumed and then transparently write to the inner AsyncWrite
=> http patch: only buffer the top of the response

http/src/conn.rs
I have been unable to observe this actually leaking memory under any instrumentation, but the documentation for std::mem::forget indicates that it could/should leak.
As of this PR there is zero usage of std::mem::forget in trillium.
=> http bugfix: address theoretical memory leak in after_send caused by std::mem::forget

http/src/after_send.rs, http/src/conn.rs, http/src/copy.rs, http/src/error.rs, http/src/http_config.rs, http/src/lib.rs, http/src/received_body.rs, http/src/received_body/tests.rs, http/src/received_body/tests/chunked.rs, http/src/received_body/tests/fixed_length.rs, http/src/synthetic.rs
additionally, partially address a bug in which polling a chunked body with a long chunk size and a short buffer never completes.
=> Bugfix: add a default limiter to received request bodies

trillium/Cargo.toml
Current trillium doesn't compile with older trillium-http, because it
imports the new `HttpConfig`. This results in a compilation error if a
project ends up with new trillium without new trillium-http.
=> trillium: Add versioned dependency on trillium-http

http/src/received_body.rs, http/src/received_body/tests/chunked.rs
This adds a test case for a network-triggered arithmetic overflow, and changes the decoding function to check for overflow. This was found with the fuzzer in #411.
=> Fix overflow in chunked body decoding

server-common/src/client.rs
The documented async trait signature didn't match the trait.
=> Fix documentation for `Connector::connect`

docs/src/overview/runtimes.md
trillium-acme helps you serve HTTPS with Trillium using automatic
certificates, via Let’s Encrypt and ACME tls-alpn-01 challenges.
I've tested this both with the staging and production Let's Encrypt
directories.
=> Add a new trillium-acme crate to automatically manage HTTPS certificates

client/src/conn.rs
this resolves the lingering intermittent test timeout
=> client bugfix: check the existing buffer before attempting to read from the transport

http/src/conn.rs, http/src/transport/boxed_transport.rs
This PR is an alternative to the approach in
https://github.com/trillium-rs/trillium/pull/432 , based on the comment at
https://github.com/trillium-rs/trillium/pull/432#discussion_r1379128491 .
I added methods on `trillium_http::Conn` to get a `&Transport` or `&mut Transport`.
I then added methods on `BoxedTransport` to downcast to a specific type
implementing `Transport`. I went with downcast methods on `BoxedTransport`
rather than exposing `as_any()` and `as_mut_any()` directly, because the latter
would have been the same amount of code and with a more complex interface.
With both of these changes, given a `trillium::Conn`, you can call
`conn.inner().transport().downcast_ref()` or
`conn.inner().transport_mut().downcast_mut()` to get your custom transport
type.
I think this is the …
=> Minimal support for downcasting to a custom transport type

http/src/conn.rs, http/src/headers.rs
=> http bugfix: case insensitive header equality was wrong

websockets/Cargo.toml, websockets/examples/json_broadcast_websocket.rs, websockets/examples/json_websocket.rs, websockets/examples/websockets.rs, websockets/src/bidirectional_stream.rs, websockets/src/json.rs, websockets/src/lib.rs, websockets/src/websocket_connection.rs, websockets/src/websocket_handler.rs, websockets/tests/json.rs, websockets/tests/test.rs
=> websockets: make error handling more explicit

http/src/copy.rs
because clippy is just like that sometimes
=> clippy: document io errors returned from the unstable-flagged trillium_http::copy

client/src/conn.rs, client/tests/one_hundred_continue.rs, http/src/conn.rs, http/src/version.rs, proxy/examples/proxy.rs, proxy/examples/upstream.rs, proxy/src/lib.rs
Across the three crates, this adds support for GET requests with bodies and reduces unnecessary headers, such as `Connection: keep-alive` (the default for http/1.1) and `Content-Length: 0` (the same as sending neither `Content-Length` nor `Transfer-Encoding: chunked`)
Nobody should use GET requests with bodies, but the proxy previously wouldn't ignore them gracefully, and kept the connection open until the other side disconnected. I don't believe this represents a security concern, but it's not particularly difficult to just check for the presence of a body instead of special-casing GET requests.
=> client, proxy, and http header tweaks

macros/Cargo.toml, macros/README.md, macros/src/async_read.rs, macros/src/async_write.rs, macros/src/handler.rs, macros/src/lib.rs, macros/src/transport.rs, macros/tests/transport.rs
Implement a proc macro for deriving `Transport`, delegating to a field.
Improve documentation in `README.md`, which did not previously document the
derives for `AsyncRead` or `AsyncWrite`.
All the commits except the last one are bugfixes; the last is the new
`derive(Transport)` macro.
=> trillium-macros: Add `derive(Transport)` macro and improve documentation

.github/workflows/ci.yaml, static/Cargo.toml, static/src/fs_shims.rs, static/src/handler.rs, static/src/lib.rs, static/src/static_conn_ext.rs
this improves the release process. When #398 releases, it'll be possible to optionally plumb an `Arc<dyn AsyncFs>` through shared state or something like that
=> allow trillium-static to build without any features enabled, panic at runtime

client/src/into_url.rs, client/tests/base.rs
- client: `impl IntoUrl for String` for convenience
- client: Add tests for using `String` with `IntoUrl`
=> client: `impl IntoUrl for String` for convenience

client/src/client.rs, client/src/conn.rs, client/src/into_url.rs, client/src/lib.rs, client/tests/base.rs
This uses `client.path_segments_mut()?.extend(…)`
=> client: impl into url for slices, arrays and vecs

client/src/lib.rs
in order to facilitate use of trillium_client without additional dependencies other than connectors
=> feat(client): reexport trillium_http::{Body, Method}

client/Cargo.toml, client/src/lib.rs, client/src/websocket.rs, client/tests/websocket.rs, websockets/Cargo.toml, websockets/src/lib.rs, websockets/src/websocket_connection.rs
Add a `websocket` feature gating support for client-side WebSocket
support. When set, provide methods on `trillium_client::Conn` that allow
upgrading to a `WebSocketConn`.
Usage:
```rust
let mut ws = client
.get(url)
.with_websocket_upgrade_headers()
.await?
.into_websocket()
.await?;
ws.send_string(format!("Hello from a WebSocket client!")).await?;
```
Having this support natively in trillium allows reusing a connection
from the connection pool when establishing a WebSocket connection
(though of course the connection cannot go *back* to the pool). It also
allows using any headers and base already set on the client. And
finally, it allows clients to avoid some of async-tungstenite's
dependencies, such as async-tls and rustls, in favor of
trillium-client's dependencies.
=>  trillium-client: Add client WebSocket support 

rustls/Cargo.toml, rustls/src/client.rs, rustls/src/server.rs
This PR adds support for using the aws-lc-rs backend of rustls.
When using a backend other than ring, rustls doesn't support
`ClientConfig::builder()` or `ServerConfig::builder()`, and instead requires
using `builder_with_provider`. Add support for using either ring or aws-lc-rs
as the provider.
This requires futures-rustls 0.25.1, which changes its rustls dependency to use
`default-features = false`.
=> trillium-rustls: Support using aws-lc-rs as a rustls backend

.github/workflows/coverage.yml, client/Cargo.toml, http/Cargo.toml, http/src/conn.rs, http/src/lib.rs, http/src/liveness.rs, testing/src/lib.rs, testing/src/runtimeless.rs, testing/src/test_transport.rs, trillium/Cargo.toml, trillium/examples/liveness.rs, trillium/src/conn.rs, trillium/tests/liveness.rs
This introduces `conn.cancel_on_disconnect(async { … }).await`, which polls the transport for empty reads (or io errors) and cancels the wrapped future, returning None. If the future completes without the client disconnecting, it will return Some with the output of the future
This PR also includes some small improvements encountered along the way
=> feat(http): cancel on disconnect

trillium/Cargo.toml
Apparently release-plz does not do this, unexpectedly. This means that updating trillium without an explicit cargo update will fail to build
=> fix(trillium): fix trillium-http dependency

router/src/lib.rs, router/src/router.rs, router/src/router_conn_ext.rs
Motivation: trillium-router should be able to update a major version of routefinder and release as a patch release if the public trillium-router interface does not change. Previously, we were leaking routefinder types through state and the RouterConnExt::route interface.
=> feat(router)!: remove routefinder types from the public api

http/src/conn.rs, http/src/synthetic.rs, testing/Cargo.toml, testing/src/runtimeless.rs, testing/src/test_transport.rs, testing/tests/cancel_on_disconnect.rs, trillium/Cargo.toml, trillium/tests/liveness.rs
Prior to this PR, `Conn<Synthetic>` and `trillium_testing::TestConn` were incompatible with disconnection testing because a cursor that has been read to end returns `Poll::Ready(Ok(0))`, which we use one indication of a closed connection.
Additionally, the logic in Conn::is_disconnected was exactly backwards because I had written it as `Conn::is_connected` and then changed the name because all usage was negating the result. However, I did not change the logic to follow the name so it was always wrong. This was possible because it was untested. Tests have now been added for Conn::is_disconnected.
=> Fix synthetic body and is_disconnected

http/tests/corpus.rs, http/tests/corpus/1.request, http/tests/corpus/1.response, http/tests/corpus/10.request, http/tests/corpus/10.response, http/tests/corpus/2.request, http/tests/corpus/2.response, http/tests/corpus/3.request, http/tests/corpus/3.response, http/tests/corpus/4.request, http/tests/corpus/4.response, http/tests/corpus/5.request, http/tests/corpus/5.response, http/tests/corpus/6.request, http/tests/corpus/6.response, http/tests/corpus/7.request, http/tests/corpus/7.response, http/tests/corpus/8.request, http/tests/corpus/8.response, http/tests/corpus/9.request, http/tests/corpus/9.response, http/tests/corpus/footers.error, http/tests/corpus/footers.request, http/tests/corpus/unsupported-http-version.error, http/tests/corpus/unsupported-http-version.request
These tests are currently descriptive, not normative. In particular, the two errors should be resolved.
The addition of these tests provides further test coverage for fully exercising the parser
=> feat(test): add corpus tests

trillium/src/handler.rs
=> feat(trillium): improve log message when calling `Arc<Handler>::init` on a clone

.cargo/config
this was only necessary for testing the aws lambda runtime
=> chore: rm .cargo/config

router/Cargo.toml
closes #552 
this wasn't worth a breaking change bump, but the next breaking change will remove the feature entirely, as there really isn't any reason a trillium user wouldn't want memchr currently
=> feat(router): enable "memchr" feature by default

router/Cargo.toml
refs #552: I had forgotten that trillium-router already had breaking changes on main
=> feat(router)!: fully remove memchr feature

proxy/src/forward_proxy_connect.rs
without this, the crate did not build with --no-default-features
closes #587
=> fix(proxy): use Connector and ObjectSafeConnector from trillium_client

channels/src/channel_central.rs, compression/src/lib.rs, head/src/lib.rs, proxy/src/upstream/connection_counting.rs, testing/src/test_conn.rs, trillium/src/conn.rs, trillium/src/state.rs, websockets/examples/json_broadcast_websocket.rs, websockets/examples/json_websocket.rs, websockets/src/json.rs, websockets/src/websocket_connection.rs, websockets/tests/json.rs, websockets/tests/test.rs
I'm on the fence about this api churn, but this was a mistake that has been bothering me for a while, and trillium hasn't had intentional breaking changes since August 2021.
I'm going to hold off on releasing this until #611 is ready, just in case there are other easily-deprecatable changes, and then I'll stagger the releases by a week or so.
=> feat: deprecate set_state for insert_state

api/Cargo.toml, api/src/error.rs, api/src/from_conn.rs, api/src/try_from_conn.rs, api/tests/disconnect-body.rs, testing/src/lib.rs
Instead of using the FromConn blanket impl with Error = ()
Closes #647
=> api: implement TryFromConn for `Vec<u8>` and `String`

rustls/Cargo.toml
rustls-platform-verifier 0.3.2 fixes a dependency issue leading
trillium-rustls to have *both* aws-lc-rs and ring in its dependencies,
even if only depending on aws-lc-rs.
Fixes: https://github.com/trillium-rs/trillium/issues/664
=> Require rustls-platform-verifier 0.3.2 to avoid multiple crypto backends
